[package]
name = "train-delay-logger"
version = "0.1.0"
authors = ["Chris Hutchinson <chris_hutchinson@me.com>"]

[dependencies]
reqwest = "0.8.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"